COMMON: &common
    PROJECT: RPiHelper
    DEBUG: False
    TESTING: False
    SECRET_KEY: insecure

    SERVICES: []

DEVELOPMENT: &development
    <<: *common
    DEBUG: True

STAGING: &staging
    <<: *common

    SERVICES:
    - {
        name: transmission,
        description: 'Torrent web interface',
        url: '/transmission/web/'
      }
    - {
        name: vsftpd,
        description: 'FTP web interface',
        url: 'ftp://192.168.1.7/'
      }

TESTING: &testing
    <<: *development
    TESTING: True
    CSRF_ENABLED: False
